import { FoodItem, Recipe, UserProfile, MealPlan, ShoppingItem } from './types';

// Mock Food Items
export const mockFoodItems: FoodItem[] = [
  {
    id: '1',
    name: 'Fresh Spinach',
    quantity: 1,
    originalQuantity: 1,
    unit: 'bag',
    category: 'Vegetables',
    calories: 23,
    expirationDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000), // 4 days from now
    addedDate: new Date(),
    status: 'fresh',
    location: 'fresh',
  },
  {
    id: '2',
    name: 'Ground Beef',
    quantity: 1,
    originalQuantity: 1,
    unit: 'lb',
    category: 'Meat',
    calories: 250,
    expirationDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    addedDate: new Date(),
    status: 'watch',
    location: 'fresh',
  },
  {
    id: '3',
    name: 'Milk',
    quantity: 1,
    originalQuantity: 1,
    unit: 'gallon',
    category: 'Dairy',
    calories: 42,
    expirationDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // 1 day from now
    addedDate: new Date(),
    status: 'expiring',
    location: 'fresh',
  },
  {
    id: '4',
    name: 'Soy Sauce',
    quantity: 1,
    originalQuantity: 1,
    unit: 'bottle',
    category: 'Condiments',
    expirationDate: new Date('2026-03-14'),
    addedDate: new Date(),
    status: 'fresh',
    location: 'pantry',
  },
  {
    id: '5',
    name: 'Sea Salt',
    quantity: 500,
    originalQuantity: 500,
    unit: 'g',
    category: 'Spices',
    expirationDate: new Date('2026-12-31'),
    addedDate: new Date(),
    status: 'fresh',
    location: 'pantry',
  },
  {
    id: '6',
    name: 'Chicken Breast',
    quantity: 2,
    originalQuantity: 2,
    unit: 'pieces',
    category: 'Meat',
    calories: 165,
    expirationDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    addedDate: new Date(),
    status: 'fresh',
    location: 'fresh',
  },
  {
    id: '7',
    name: 'Tomatoes',
    quantity: 4,
    originalQuantity: 4,
    unit: 'medium',
    category: 'Vegetables',
    calories: 22,
    expirationDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    addedDate: new Date(),
    status: 'fresh',
    location: 'fresh',
  },
  {
    id: '8',
    name: 'Onions',
    quantity: 3,
    originalQuantity: 3,
    unit: 'medium',
    category: 'Vegetables',
    calories: 44,
    expirationDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    addedDate: new Date(),
    status: 'fresh',
    location: 'fresh',
  },
  {
    id: '9',
    name: 'Garlic',
    quantity: 1,
    originalQuantity: 1,
    unit: 'head',
    category: 'Vegetables',
    calories: 4,
    expirationDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    addedDate: new Date(),
    status: 'fresh',
    location: 'fresh',
  },
  {
    id: '10',
    name: 'Olive Oil',
    quantity: 1,
    originalQuantity: 1,
    unit: 'bottle',
    category: 'Oils',
    expirationDate: new Date('2025-12-31'),
    addedDate: new Date(),
    status: 'fresh',
    location: 'pantry',
  },
];

// Comprehensive Mock Recipes for Development
export const mockRecipes: Recipe[] = [
  // Quick & Easy Recipes
  {
    id: '1',
    name: 'Chinese Beef Stir Fry',
    cuisine: 'Chinese',
    time: '20 mins',
    ingredients: [
      { name: 'Ground Beef', amount: 1, unit: 'lb' },
      { name: 'Spinach', amount: 2, unit: 'cups' },
      { name: 'Soy Sauce', amount: 2, unit: 'tbsp' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Onions', amount: 1, unit: 'medium' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Heat oil in a wok over high heat',
      'Add beef and stir-fry until browned',
      'Add garlic and onions, stir for 30 seconds',
      'Add spinach and soy sauce',
      'Cook until spinach wilts, about 2 minutes',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 350,
    tags: ['quick', 'healthy', 'asian'],
  },
  {
    id: '2',
    name: 'Creamy Spinach Soup',
    cuisine: 'Western',
    time: '15 mins',
    ingredients: [
      { name: 'Spinach', amount: 4, unit: 'cups' },
      { name: 'Milk', amount: 2, unit: 'cups' },
      { name: 'Onions', amount: 1, unit: 'medium' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté onion and garlic in oil until translucent',
      'Add spinach and cook until wilted',
      'Add milk and simmer for 5 minutes',
      'Blend until smooth',
      'Season with salt and pepper',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 180,
    tags: ['vegetarian', 'soup', 'quick'],
  },
  {
    id: '3',
    name: 'Grilled Chicken Salad',
    cuisine: 'American',
    time: '25 mins',
    ingredients: [
      { name: 'Chicken Breast', amount: 2, unit: 'pieces' },
      { name: 'Spinach', amount: 4, unit: 'cups' },
      { name: 'Tomatoes', amount: 2, unit: 'medium' },
      { name: 'Onions', amount: 0.5, unit: 'medium' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Season chicken with salt and pepper',
      'Grill chicken for 6-8 minutes per side',
      'Chop vegetables and mix in bowl',
      'Slice grilled chicken and add to salad',
      'Drizzle with olive oil and serve',
    ],
    difficulty: 'easy',
    servings: 2,
    calories: 320,
    tags: ['healthy', 'salad', 'protein'],
  },
  {
    id: '4',
    name: 'Tomato Basil Pasta',
    cuisine: 'Italian',
    time: '20 mins',
    ingredients: [
      { name: 'Pasta', amount: 8, unit: 'oz' },
      { name: 'Tomatoes', amount: 4, unit: 'medium' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Olive Oil', amount: 3, unit: 'tbsp' },
      { name: 'Sea Salt', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      'Cook pasta according to package directions',
      'Sauté garlic in olive oil until fragrant',
      'Add chopped tomatoes and cook for 5 minutes',
      'Toss with cooked pasta',
      'Season with salt and serve',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 280,
    tags: ['vegetarian', 'pasta', 'quick'],
  },
  {
    id: '5',
    name: 'Beef and Onion Stir Fry',
    cuisine: 'Chinese',
    time: '15 mins',
    ingredients: [
      { name: 'Ground Beef', amount: 1, unit: 'lb' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Soy Sauce', amount: 3, unit: 'tbsp' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Heat oil in a large pan',
      'Add beef and cook until browned',
      'Add onions and garlic',
      'Stir in soy sauce',
      'Cook until onions are tender',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 300,
    tags: ['quick', 'beef', 'asian'],
  },
  {
    id: '6',
    name: 'Spinach and Tomato Omelette',
    cuisine: 'French',
    time: '10 mins',
    ingredients: [
      { name: 'Eggs', amount: 3, unit: 'large' },
      { name: 'Spinach', amount: 1, unit: 'cup' },
      { name: 'Tomatoes', amount: 1, unit: 'medium' },
      { name: 'Milk', amount: 2, unit: 'tbsp' },
      { name: 'Olive Oil', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Whisk eggs with milk',
      'Sauté spinach and tomatoes briefly',
      'Pour egg mixture over vegetables',
      'Cook until set',
      'Fold and serve',
    ],
    difficulty: 'easy',
    servings: 1,
    calories: 250,
    tags: ['breakfast', 'vegetarian', 'quick'],
  },
  {
    id: '7',
    name: 'Chicken and Spinach Curry',
    cuisine: 'Indian',
    time: '30 mins',
    ingredients: [
      { name: 'Chicken Breast', amount: 2, unit: 'pieces' },
      { name: 'Spinach', amount: 3, unit: 'cups' },
      { name: 'Onions', amount: 1, unit: 'medium' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Tomatoes', amount: 2, unit: 'medium' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté onions and garlic in oil',
      'Add chicken and cook until browned',
      'Add tomatoes and cook for 5 minutes',
      'Add spinach and simmer',
      'Season with curry spices',
    ],
    difficulty: 'medium',
    servings: 4,
    calories: 280,
    tags: ['curry', 'chicken', 'spicy'],
  },
  {
    id: '8',
    name: 'Mediterranean Salad',
    cuisine: 'Mediterranean',
    time: '15 mins',
    ingredients: [
      { name: 'Spinach', amount: 4, unit: 'cups' },
      { name: 'Tomatoes', amount: 3, unit: 'medium' },
      { name: 'Onions', amount: 0.5, unit: 'medium' },
      { name: 'Olive Oil', amount: 3, unit: 'tbsp' },
      { name: 'Sea Salt', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Wash and prepare all vegetables',
      'Chop tomatoes and onions',
      'Mix all ingredients in a bowl',
      'Drizzle with olive oil',
      'Season with salt and serve',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 120,
    tags: ['vegetarian', 'salad', 'healthy'],
  },
  {
    id: '9',
    name: 'Beef and Tomato Stew',
    cuisine: 'American',
    time: '45 mins',
    ingredients: [
      { name: 'Ground Beef', amount: 1.5, unit: 'lb' },
      { name: 'Tomatoes', amount: 4, unit: 'medium' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Brown beef in oil',
      'Add onions and garlic',
      'Add tomatoes and simmer',
      'Cook for 30 minutes',
      'Season to taste',
    ],
    difficulty: 'medium',
    servings: 6,
    calories: 380,
    tags: ['stew', 'beef', 'comfort'],
  },
  {
    id: '10',
    name: 'Spinach and Garlic Pasta',
    cuisine: 'Italian',
    time: '20 mins',
    ingredients: [
      { name: 'Pasta', amount: 12, unit: 'oz' },
      { name: 'Spinach', amount: 3, unit: 'cups' },
      { name: 'Garlic', amount: 6, unit: 'cloves' },
      { name: 'Olive Oil', amount: 4, unit: 'tbsp' },
      { name: 'Sea Salt', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      'Cook pasta al dente',
      'Sauté garlic in olive oil',
      'Add spinach and wilt',
      'Toss with pasta',
      'Season with salt',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 320,
    tags: ['vegetarian', 'pasta', 'garlic'],
  },
  {
    id: '11',
    name: 'Chicken Tomato Soup',
    cuisine: 'American',
    time: '25 mins',
    ingredients: [
      { name: 'Chicken Breast', amount: 2, unit: 'pieces' },
      { name: 'Tomatoes', amount: 6, unit: 'medium' },
      { name: 'Onions', amount: 1, unit: 'medium' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté chicken in oil',
      'Add vegetables and cook',
      'Add water and simmer',
      'Cook for 15 minutes',
      'Season and serve',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 220,
    tags: ['soup', 'chicken', 'comfort'],
  },
  {
    id: '12',
    name: 'Beef and Onion Tacos',
    cuisine: 'Mexican',
    time: '20 mins',
    ingredients: [
      { name: 'Ground Beef', amount: 1, unit: 'lb' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Tomatoes', amount: 2, unit: 'medium' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Olive Oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook beef in oil',
      'Add onions and garlic',
      'Add tomatoes',
      'Cook until thickened',
      'Serve in tortillas',
    ],
    difficulty: 'easy',
    servings: 4,
    calories: 350,
    tags: ['tacos', 'beef', 'mexican'],
  },
  {
    id: '13',
    name: 'Spinach and Tomato Quiche',
    cuisine: 'French',
    time: '50 mins',
    ingredients: [
      { name: 'Spinach', amount: 2, unit: 'cups' },
      { name: 'Tomatoes', amount: 3, unit: 'medium' },
      { name: 'Eggs', amount: 4, unit: 'large' },
      { name: 'Milk', amount: 1, unit: 'cup' },
      { name: 'Onions', amount: 1, unit: 'medium' },
    ],
    instructions: [
      'Preheat oven to 375°F',
      'Sauté vegetables',
      'Mix eggs and milk',
      'Combine and bake',
      'Cook for 35 minutes',
    ],
    difficulty: 'medium',
    servings: 6,
    calories: 280,
    tags: ['vegetarian', 'quiche', 'brunch'],
  },
  {
    id: '14',
    name: 'Chicken and Spinach Wrap',
    cuisine: 'American',
    time: '15 mins',
    ingredients: [
      { name: 'Chicken Breast', amount: 1, unit: 'piece' },
      { name: 'Spinach', amount: 2, unit: 'cups' },
      { name: 'Tomatoes', amount: 1, unit: 'medium' },
      { name: 'Onions', amount: 0.5, unit: 'medium' },
      { name: 'Olive Oil', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Grill chicken',
      'Chop vegetables',
      'Warm tortilla',
      'Assemble wrap',
      'Serve immediately',
    ],
    difficulty: 'easy',
    servings: 2,
    calories: 320,
    tags: ['wrap', 'chicken', 'quick'],
  },
  {
    id: '15',
    name: 'Beef and Tomato Casserole',
    cuisine: 'American',
    time: '60 mins',
    ingredients: [
      { name: 'Ground Beef', amount: 2, unit: 'lb' },
      { name: 'Tomatoes', amount: 6, unit: 'medium' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Milk', amount: 1, unit: 'cup' },
    ],
    instructions: [
      'Brown beef with vegetables',
      'Layer in casserole dish',
      'Add milk mixture',
      'Bake at 350°F',
      'Cook for 45 minutes',
    ],
    difficulty: 'medium',
    servings: 8,
    calories: 420,
    tags: ['casserole', 'beef', 'comfort'],
  },
];

// Mock User Profile
export const mockUserProfile: UserProfile = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex.johnson@email.com',
  avatar: require('../assets/icon.png'),
  dietPreferences: ['Vegetarian', 'Gluten-Free'],
  favoriteCuisine: 'Italian',
  allergies: ['Peanuts'],
  calorieGoal: 2000,
  createdAt: new Date(),
  updatedAt: new Date(),
};

// Mock Meal Plans
export const mockMealPlans: MealPlan[] = [
  {
    id: '1',
    date: '2024-01-15',
    meals: {
      breakfast: mockRecipes[5], // Spinach and Tomato Omelette
      lunch: mockRecipes[0], // Chinese Beef Stir Fry
      dinner: mockRecipes[1], // Creamy Spinach Soup
    },
    notes: 'Using up spinach before it expires',
  },
  {
    id: '2',
    date: '2024-01-16',
    meals: {
      breakfast: mockRecipes[1], // Creamy Spinach Soup
      lunch: mockRecipes[2], // Grilled Chicken Salad
      dinner: mockRecipes[0], // Chinese Beef Stir Fry
    },
  },
];

// Mock Shopping List
export const mockShoppingItems: ShoppingItem[] = [
  {
    id: '1',
    name: 'Bananas',
    quantity: 6,
    unit: 'pieces',
    category: 'Fruits',
    completed: false,
    addedDate: new Date(),
  },
  {
    id: '2',
    name: 'Whole Wheat Bread',
    quantity: 1,
    unit: 'loaf',
    category: 'Bakery',
    completed: true,
    addedDate: new Date(),
  },
  {
    id: '3',
    name: 'Greek Yogurt',
    quantity: 2,
    unit: 'cups',
    category: 'Dairy',
    completed: false,
    addedDate: new Date(),
  },
]; 